spring:
  datasource:
    username: admin
    password: wswzHJSC
    url: jdbc:mysql://154.8.236.68:3306/risunking?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    schema:
      - classpath:risunking.sql
    initialization-mode: always
    continue-on-error: false
  jackson:
    default-property-inclusion: non_null
server:
  port: 9999
logging:
  config:
    - classpath:logback-boot.xml
mybatis:
  mapper-locations:
    - classpath:mybatis/**/**.xml